version: '2.3'

services:
  base:
    build:
      context: .
      args: 
        - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.example

  postgres:
    container_name: postgres
    image: postgres:11.7-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=500MB"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30

  elasticsearch:
    container_name: elasticsearch
    image: blacktop/elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - ELASTIC_PASSWORD=changeme
    healthcheck:
      test: ["CMD", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    container_name: redis
    image: redis:6-alpine
    command: redis-server --requirepass secret
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4

  sqs:
    container_name: sqs
    image: roribio16/alpine-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./src/data-sources/sqs/local-setup.conf:/opt/config/elasticmq.conf

  migrate:
    extends: base
    entrypoint: npm run migrate
    depends_on:
      - postgres
  
  rest-server:
    container_name: rest-server
    extends: base
    command: npm run start:rest-server
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - migrate
    environment: 
      - APP_NAME=rest_server
      - APP_TYPE=server
      - DATABASE_MAX_CONNECTIONS=100

  grpc-server:
    container_name: grpc-server
    extends: base
    command: npm run start:grpc-server
    ports:
      - "3001:3001"
    links:
      - postgres
    depends_on:
      - migrate
    environment: 
      - APP_NAME=grpc_server
      - APP_TYPE=server
      - DATABASE_MAX_CONNECTIONS=100

  transfer-processor-worker:
    container_name: transfer-processor-worker
    extends: base
    command: npm run start:transfer-kafka-processor-worker
    links:
      - postgres
      - kafka
    depends_on:
      - migrate
      - kafka
    environment: 
      - APP_NAME=transfer_processor_worker
      - APP_TYPE=worker
      - DATABASE_MAX_CONNECTIONS=50

  transfer-creation-worker:
    container_name: transfer-creation-worker
    extends: base
    command: npm run start:transfer-sqs-creation-worker
    links:
      - postgres
      - sqs
    depends_on:
      - migrate
      - sqs
    environment: 
      - APP_NAME=transfer_creation_worker
      - APP_TYPE=worker
      - DATABASE_MAX_CONNECTIONS=50

  repl:
    container_name: repl
    extends: base
    command: npm run start:repl
    links:
      - postgres
      - sqs
    depends_on:
      - migrate
      - sqs
    environment: 
      - APP_NAME=repl
      - APP_TYPE=repl
      - DATABASE_MAX_CONNECTIONS=10

  tests:
    container_name: tests
    extends: base
    command: npm run test
    depends_on:
      migrate:
        condition: service_started
      sqs:
        condition: service_started
      elasticsearch:
        condition: service_started
      redis: 
        condition: service_healthy
      kafka:
        condition: service_started